#!/bin/bash
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Chisel --w_dir=../DAC_results/llama3-405b/HDLEval-comb/Chisel/simple --lec_limit=1 --comp_limit=1 hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Chisel --w_dir=../DAC_results/llama3-405b/HDLEval-comb/Chisel/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/Chisel/Chisel_examples.md hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Chisel --w_dir=../DAC_results/llama3-405b/HDLEval-comb/Chisel/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/Chisel/chisel_reference_sum1_gpt.md hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Chisel --w_dir=../DAC_results/llama3-405b/HDLEval-comb/Chisel/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/Chisel/chisel_reference_sum1_gpt.md --supp_context hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Chisel --w_dir=../DAC_results/llama3-405b/HDLEval-pipe/Chisel/simple --lec_limit=1 --comp_limit=1 hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Chisel --w_dir=../DAC_results/llama3-405b/HDLEval-pipe/Chisel/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/Chisel/Chisel_examples.md hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Chisel --w_dir=../DAC_results/llama3-405b/HDLEval-pipe/Chisel/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/Chisel/chisel_reference_sum1_gpt.md hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Chisel --w_dir=../DAC_results/llama3-405b/HDLEval-pipe/Chisel/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/Chisel/chisel_reference_sum1_gpt.md --supp_context hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Chisel --w_dir=../DAC_results/llama3-405b/VerilogEval2-comb/Chisel/simple --lec_limit=1 --comp_limit=1 hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Chisel --w_dir=../DAC_results/llama3-405b/VerilogEval2-comb/Chisel/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/Chisel/Chisel_examples.md hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Chisel --w_dir=../DAC_results/llama3-405b/VerilogEval2-comb/Chisel/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/Chisel/chisel_reference_sum1_gpt.md hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Chisel --w_dir=../DAC_results/llama3-405b/VerilogEval2-comb/Chisel/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/Chisel/chisel_reference_sum1_gpt.md --supp_context hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Chisel --w_dir=../DAC_results/llama3-405b/VerilogEval2-pipe/Chisel/simple --lec_limit=1 --comp_limit=1 hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Chisel --w_dir=../DAC_results/llama3-405b/VerilogEval2-pipe/Chisel/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/Chisel/Chisel_examples.md hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Chisel --w_dir=../DAC_results/llama3-405b/VerilogEval2-pipe/Chisel/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/Chisel/chisel_reference_sum1_gpt.md hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Chisel --w_dir=../DAC_results/llama3-405b/VerilogEval2-pipe/Chisel/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/Chisel/chisel_reference_sum1_gpt.md --supp_context hdeval:VerilogEval2-pipe
