#!/bin/bash

timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gpt-4-1106-preview --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gpt-4-1106-preview/VerilogEval2-comb/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gpt-4-1106-preview --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gpt-4-1106-preview/VerilogEval2-comb/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gpt-4-1106-preview --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gpt-4-1106-preview/VerilogEval2-comb/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gpt-4-1106-preview --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gpt-4-1106-preview/VerilogEval2-comb/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gpt-4-1106-preview --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gpt-4-1106-preview/VerilogEval2-pipe/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gpt-4-1106-preview --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gpt-4-1106-preview/VerilogEval2-pipe/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gpt-4-1106-preview --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gpt-4-1106-preview/VerilogEval2-pipe/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gpt-4-1106-preview --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gpt-4-1106-preview/VerilogEval2-pipe/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:VerilogEval2-pipe

timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gpt-3.5-turbo-0125 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gpt-3.5-turbo-0125/VerilogEval2-comb/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gpt-3.5-turbo-0125 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gpt-3.5-turbo-0125/VerilogEval2-comb/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gpt-3.5-turbo-0125 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gpt-3.5-turbo-0125/VerilogEval2-comb/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gpt-3.5-turbo-0125 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gpt-3.5-turbo-0125/VerilogEval2-comb/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gpt-3.5-turbo-0125 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gpt-3.5-turbo-0125/VerilogEval2-pipe/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gpt-3.5-turbo-0125 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gpt-3.5-turbo-0125/VerilogEval2-pipe/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gpt-3.5-turbo-0125 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gpt-3.5-turbo-0125/VerilogEval2-pipe/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gpt-3.5-turbo-0125 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gpt-3.5-turbo-0125/VerilogEval2-pipe/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:VerilogEval2-pipe

timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gpt-3.5-turbo-1106 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gpt-3.5-turbo-1106/VerilogEval2-comb/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gpt-3.5-turbo-1106 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gpt-3.5-turbo-1106/VerilogEval2-comb/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gpt-3.5-turbo-1106 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gpt-3.5-turbo-1106/VerilogEval2-comb/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gpt-3.5-turbo-1106 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gpt-3.5-turbo-1106/VerilogEval2-comb/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gpt-3.5-turbo-1106 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gpt-3.5-turbo-1106/VerilogEval2-pipe/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gpt-3.5-turbo-1106 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gpt-3.5-turbo-1106/VerilogEval2-pipe/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gpt-3.5-turbo-1106 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gpt-3.5-turbo-1106/VerilogEval2-pipe/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gpt-3.5-turbo-1106 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gpt-3.5-turbo-1106/VerilogEval2-pipe/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:VerilogEval2-pipe

timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/HDLEval-comb/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/HDLEval-comb/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/HDLEval-comb/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/HDLEval-comb/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/HDLEval-pipe/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/HDLEval-pipe/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/HDLEval-pipe/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/HDLEval-pipe/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/VerilogEval2-comb/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/VerilogEval2-comb/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/VerilogEval2-comb/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/VerilogEval2-comb/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/VerilogEval2-pipe/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/VerilogEval2-pipe/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/VerilogEval2-pipe/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/VerilogEval2-pipe/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-70B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-70B-Instruct/HDLEval-comb/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-70B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-70B-Instruct/HDLEval-comb/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-70B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-70B-Instruct/HDLEval-comb/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-70B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-70B-Instruct/HDLEval-comb/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-70B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-70B-Instruct/HDLEval-pipe/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-70B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-70B-Instruct/HDLEval-pipe/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-70B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-70B-Instruct/HDLEval-pipe/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-70B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-70B-Instruct/HDLEval-pipe/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-70B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-70B-Instruct/VerilogEval2-comb/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-70B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-70B-Instruct/VerilogEval2-comb/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-70B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-70B-Instruct/VerilogEval2-comb/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-70B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-70B-Instruct/VerilogEval2-comb/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-70B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-70B-Instruct/VerilogEval2-pipe/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-70B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-70B-Instruct/VerilogEval2-pipe/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-70B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-70B-Instruct/VerilogEval2-pipe/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-70B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-70B-Instruct/VerilogEval2-pipe/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-405B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-405B-Instruct/HDLEval-comb/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-405B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-405B-Instruct/HDLEval-comb/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-405B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-405B-Instruct/HDLEval-comb/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-405B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-405B-Instruct/HDLEval-comb/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-405B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-405B-Instruct/HDLEval-pipe/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-405B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-405B-Instruct/HDLEval-pipe/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-405B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-405B-Instruct/HDLEval-pipe/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-405B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-405B-Instruct/HDLEval-pipe/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-405B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-405B-Instruct/VerilogEval2-comb/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-405B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-405B-Instruct/VerilogEval2-comb/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-405B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-405B-Instruct/VerilogEval2-comb/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-405B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-405B-Instruct/VerilogEval2-comb/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-405B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-405B-Instruct/VerilogEval2-pipe/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-405B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-405B-Instruct/VerilogEval2-pipe/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-405B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-405B-Instruct/VerilogEval2-pipe/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=Meta-Llama-3.1-405B-Instruct --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/Meta-Llama-3.1-405B-Instruct/VerilogEval2-pipe/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:VerilogEval2-pipe
