#!/bin/bash
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=DSLX --w_dir=../DAC_results/llama3-405b/HDLEval-comb/DSLX/simple --lec_limit=1 --comp_limit=1 hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=DSLX --w_dir=../DAC_results/llama3-405b/HDLEval-comb/DSLX/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/DSLX/DSLX_examples.md hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=DSLX --w_dir=../DAC_results/llama3-405b/HDLEval-comb/DSLX/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/DSLX/dslx_reference_sum2_gemini.md hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=DSLX --w_dir=../DAC_results/llama3-405b/HDLEval-comb/DSLX/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/DSLX/dslx_reference_sum2_gemini.md --supp_context hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=DSLX --w_dir=../DAC_results/llama3-405b/VerilogEval2-comb/DSLX/simple --lec_limit=1 --comp_limit=1 hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=DSLX --w_dir=../DAC_results/llama3-405b/VerilogEval2-comb/DSLX/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/DSLX/DSLX_examples.md hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=DSLX --w_dir=../DAC_results/llama3-405b/VerilogEval2-comb/DSLX/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/DSLX/dslx_reference_sum2_gemini.md hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=DSLX --w_dir=../DAC_results/llama3-405b/VerilogEval2-comb/DSLX/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/DSLX/dslx_reference_sum2_gemini.md --supp_context hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=DSLX --w_dir=../DAC_results/llama3-405b/VerilogEval2-pipe/DSLX/simple --lec_limit=1 --comp_limit=1 hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=DSLX --w_dir=../DAC_results/llama3-405b/VerilogEval2-pipe/DSLX/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/DSLX/DSLX_examples.md hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=DSLX --w_dir=../DAC_results/llama3-405b/VerilogEval2-pipe/DSLX/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/DSLX/dslx_reference_sum2_gemini.md hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=DSLX --w_dir=../DAC_results/llama3-405b/VerilogEval2-pipe/DSLX/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/DSLX/dslx_reference_sum2_gemini.md --supp_context hdeval:VerilogEval2-pipe
