#!/bin/bash
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Verilog --w_dir=../DAC_results/llama3-405b/HDLEval-comb/Verilog/simple --lec_limit=1 --comp_limit=1 hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Verilog --w_dir=../DAC_results/llama3-405b/HDLEval-comb/Verilog/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/Verilog/Verilog_examples.md hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Verilog --w_dir=../DAC_results/llama3-405b/HDLEval-comb/Verilog/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/Verilog/Verilog_context_1.md hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Verilog --w_dir=../DAC_results/llama3-405b/HDLEval-comb/Verilog/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/Verilog/Verilog_context_1.md --supp_context hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Verilog --w_dir=../DAC_results/llama3-405b/HDLEval-pipe/Verilog/simple --lec_limit=1 --comp_limit=1 hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Verilog --w_dir=../DAC_results/llama3-405b/HDLEval-pipe/Verilog/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/Verilog/Verilog_examples.md hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Verilog --w_dir=../DAC_results/llama3-405b/HDLEval-pipe/Verilog/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/Verilog/Verilog_context_1.md hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Verilog --w_dir=../DAC_results/llama3-405b/HDLEval-pipe/Verilog/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/Verilog/Verilog_context_1.md --supp_context hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Verilog --w_dir=../DAC_results/llama3-405b/VerilogEval2-comb/Verilog/simple --lec_limit=1 --comp_limit=1 hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Verilog --w_dir=../DAC_results/llama3-405b/VerilogEval2-comb/Verilog/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/Verilog/Verilog_examples.md hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Verilog --w_dir=../DAC_results/llama3-405b/VerilogEval2-comb/Verilog/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/Verilog/Verilog_context_1.md hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Verilog --w_dir=../DAC_results/llama3-405b/VerilogEval2-comb/Verilog/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/Verilog/Verilog_context_1.md --supp_context hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Verilog --w_dir=../DAC_results/llama3-405b/VerilogEval2-pipe/Verilog/simple --lec_limit=1 --comp_limit=1 hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Verilog --w_dir=../DAC_results/llama3-405b/VerilogEval2-pipe/Verilog/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/Verilog/Verilog_examples.md hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Verilog --w_dir=../DAC_results/llama3-405b/VerilogEval2-pipe/Verilog/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/Verilog/Verilog_context_1.md hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=Verilog --w_dir=../DAC_results/llama3-405b/VerilogEval2-pipe/Verilog/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/Verilog/Verilog_context_1.md --supp_context hdeval:VerilogEval2-pipe
