#!/bin/bash
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.0-pro-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.0-pro-002/HDLEval-comb/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.0-pro-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.0-pro-002/HDLEval-comb/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.0-pro-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.0-pro-002/HDLEval-comb/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.0-pro-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.0-pro-002/HDLEval-comb/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.0-pro-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.0-pro-002/HDLEval-pipe/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.0-pro-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.0-pro-002/HDLEval-pipe/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.0-pro-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.0-pro-002/HDLEval-pipe/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.0-pro-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.0-pro-002/HDLEval-pipe/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.0-pro-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.0-pro-002/VerilogEval2-comb/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.0-pro-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.0-pro-002/VerilogEval2-comb/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.0-pro-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.0-pro-002/VerilogEval2-comb/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.0-pro-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.0-pro-002/VerilogEval2-comb/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.0-pro-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.0-pro-002/VerilogEval2-pipe/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.0-pro-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.0-pro-002/VerilogEval2-pipe/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.0-pro-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.0-pro-002/VerilogEval2-pipe/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.0-pro-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.0-pro-002/VerilogEval2-pipe/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/HDLEval-comb/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/HDLEval-comb/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/HDLEval-comb/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/HDLEval-comb/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/HDLEval-pipe/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/HDLEval-pipe/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/HDLEval-pipe/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/HDLEval-pipe/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/VerilogEval2-comb/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/VerilogEval2-comb/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/VerilogEval2-comb/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/VerilogEval2-comb/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/VerilogEval2-pipe/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/VerilogEval2-pipe/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/VerilogEval2-pipe/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=gemini-1.5-flash-002 --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/gemini-1.5-flash-002/VerilogEval2-pipe/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/llama3-405b/HDLEval-comb/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/llama3-405b/HDLEval-comb/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/llama3-405b/HDLEval-comb/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/llama3-405b/HDLEval-comb/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:24a --top_k=10
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/llama3-405b/HDLEval-pipe/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/llama3-405b/HDLEval-pipe/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/llama3-405b/HDLEval-pipe/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/llama3-405b/HDLEval-pipe/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:24a_pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/llama3-405b/VerilogEval2-comb/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/llama3-405b/VerilogEval2-comb/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/llama3-405b/VerilogEval2-comb/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/llama3-405b/VerilogEval2-comb/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:VerilogEval2-comb
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/llama3-405b/VerilogEval2-pipe/PyRTL/simple --lec_limit=1 --comp_limit=1 hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/llama3-405b/VerilogEval2-pipe/PyRTL/few_shot --lec_limit=1 --comp_limit=1 --init_context hdlagent/resources/PyRTL/PyRTL_examples.md hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/llama3-405b/VerilogEval2-pipe/PyRTL/init --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md hdeval:VerilogEval2-pipe
timeout 4000 poetry run hdlagent/cli_agent.py bench --llm=llama3-405b --skip_successful --skip_completed --lang=PyRTL --w_dir=../DAC_results/llama3-405b/VerilogEval2-pipe/PyRTL/supp --lec_limit=1 --comp_limit=8 --init_context hdlagent/resources/PyRTL/pyrtl_reference_sum1_gpt.md --supp_context hdeval:VerilogEval2-pipe
