#!/bin/bash
f=$1
yosys -p "logger -nowarn assigned; read_verilog -sv ${f}; proc; write_verilog tmp.dump_$$" &> tmp.yosys_$$;

grep "ERR" tmp.yosys_$$* | grep -Eiv "Suppress";
if [[ $? -ne 0 ]]; then
    grep "Warning:" tmp.yosys_$$* | grep -Eiv "Suppress";
    if [[ $? -ne 0 ]]; then
         echo "SUCCESS";
    fi
fi
grep "input" tmp.dump_$$*
grep "output" tmp.dump_$$*
rm tmp.yosys_$$;
rm tmp.dump_$$;
