#!/bin/bash
f=$1

if [ ! -s "$f" ]; then
    echo "Error: no code was received" >&2
    exit 1
fi

temp_file=$(mktemp log_check_verilog.XXXXXX)
#if which slang >/dev/null; then
#	slang -q --error-limit 1 ${f} 2>${temp_file}
#	if [[ $? -ne 0 ]]; then
#		cat ${temp_file}
#        echo "slang fail"
#        exit
#	fi
#fi

yosys -p "logger -nowarn assigned; read_verilog -sv ${f};" &>${temp_file}
if [[ $? -eq 0 ]]; then
	grep -E "Warning:|ERROR:" ${temp_file} | grep -Eiv "Suppress"
	if [[ $? -eq 0 ]]; then
		exit
    fi
fi


iverilog -g2005-sv ${f} 2>${temp_file}
grep -E "error" ${temp_file}
if [[ $? -eq 0 ]]; then
    exit
fi


echo "SUCCESS"
